version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-fudbal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: football_club
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j-db:
    image: neo4j:5.12-community
    container_name: neo4j-fudbal
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

  influx-db:
    image: influxdb:2.7-alpine
    container_name: influx-fudbal
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=vule_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=NEKA_JAKO_SIGURNA_SIFRA_123
      - DOCKER_INFLUXDB_INIT_ORG=moj-fudbalski-klub
      - DOCKER_INFLUXDB_INIT_BUCKET=match-tracking
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MOJ_SUPER_TAJNI_INFLUXDB_TOKEN_KOJI_PROSTIRE_DO_BAZE
    volumes:
      - influxdb_data:/var/lib/influxdb2

  app:
    build: .
    container_name: fudbalski-klub-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - neo4j-db
      - influx-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/football_club
      SPRING_NEO4J_URI: bolt://neo4j-db:7687
      INFLUXDB_URL: http://influx-db:8086
      INFLUXDB_TOKEN: MOJ_SUPER_TAJNI_INFLUXDB_TOKEN_KOJI_PROSTIRE_DO_BAZE

volumes:
  postgres_data:
  neo4j_data:
  influxdb_data: