spring.application.name=fudbalski_klub
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/football_club}
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=a-valid-string-secret-that-is-at-least-512-bits-long-which-is-very-long

influxdb.url=${INFLUXDB_URL:http://influx-db:8086}
influxdb.token=${INFLUXDB_TOKEN:MOJ_SUPER_TAJNI_INFLUXDB_TOKEN_KOJI_PROSTIRE_DO_BAZE}
influxdb.org=moj-fudbalski-klub
influxdb.bucket=match-tracking

spring.neo4j.uri=${SPRING_NEO4J_URI:bolt://neo4j-db:7687}
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password